### ISSUE TITLE
check if autostart permission is active for my app

### ISSUE THREAD

**Issue by Kassan424kh** [judemanutd/AutoStarter#61] opened 2021-01-27 22:10 UTC
Every time i open the app, it would open autostart settings window, how can I check if the `autostart` permission is selected before open the `settings` window?
do you have any idea?

```
class MainActivity : FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        if (AutoStartPermissionHelper.getInstance().isAutoStartPermissionAvailable(context))
            AutoStartPermissionHelper.getInstance().getAutoStartPermission(context)
    }
}
```

**Comment by judemanutd** [comment] 2021-03-31 07:33
Closing since this is a duplicate of #4 , given that these aren't standard android apis, there is no way of knowing this information.

**Closed by judemanutd** 2021-03-31 07:33 UTC
Labels: duplicate
